-- Su dung trong form gui rut
USE NGANHANG
GO
CREATE OR ALTER VIEW uv_SoDuTaiKhoan
AS
SELECT SOTK, SODU, HOTEN = kh.HO + ' ' + kh.TEN FROM (SELECT SOTK, SODU, CMND FROM NGANHANG.dbo.TaiKhoan) tk 
INNER JOIN (SELECT CMND, HO, TEN FROM LINK2.NGANHANG.dbo.KhachHang) kh 
ON tk.CMND = kh.CMND 





