USE NGANHANG
GO
CREATE  PROC [dbo].[SP_LayThongTinNhanVien]
@TENLOGIN NVARCHAR (50)
AS
DECLARE @TENUSER NVARCHAR(50), @UID INT
SELECT @UID= UID, @TENUSER=NAME FROM sys.sysusers
 WHERE sid = SUSER_SID(@TENLOGIN)
SELECT MANV = @TENUSER,
 HOTEN = (SELECT HO+ ' '+ TEN FROM NhanVien WHERE MANV = @TENUSER ),
 TENNHOM= NAME
 FROM sys.sysusers
 WHERE UID = (SELECT GROUPUID 
 FROM SYS.SYSMEMBERS
 WHERE MEMBERUID= @UID)



-- EXEC SP_TAOLOGIN 'PT', 'kc', '001' , 'NganHang'
-- EXEC SP_LayThongTinNhanVien 'lam'

 
 -- DROP PROC SP_LayThongTinNhanVien